import type {ProductItem} from "./product-list-item";

const products: ProductItem[] = [
  {
    id: "1",
    name: "Training shoes",
    href: "#",
    price: 49.99,
    color: "black",
    size: "42",
    imageSrc: "https://nextuipro.nyc3.cdn.digitaloceanspaces.com/components-images/shoes/1.png",
  },
  {
    id: "2",
    name: "Sneakers",
    href: "#",
    price: 29.99,
    color: "red",
    size: "42",
    imageSrc: "https://nextuipro.nyc3.cdn.digitaloceanspaces.com/components-images/shoes/11.png",
  },
  {
    id: "3",
    name: "Running shoes",
    href: "#",
    price: 39.99,
    color: "blue",
    size: "42",
    imageSrc: "https://nextuipro.nyc3.cdn.digitaloceanspaces.com/components-images/shoes/10.png",
  },
  {
    id: "4",
    name: "Training shoes",
    href: "#",
    price: 49.99,
    color: "black",
    size: "42",
    imageSrc: "https://nextuipro.nyc3.cdn.digitaloceanspaces.com/components-images/shoes/31.png",
  },
  {
    id: "5",
    name: "Sneakers",
    href: "#",
    price: 29.99,
    color: "red",
    size: "42",
    imageSrc: "https://nextuipro.nyc3.cdn.digitaloceanspaces.com/components-images/shoes/34.png",
  },
  {
    id: "6",
    name: "Running shoes",
    href: "#",
    price: 39.99,
    color: "blue",
    size: "42",
    imageSrc: "https://nextuipro.nyc3.cdn.digitaloceanspaces.com/components-images/shoes/6.png",
  },
  {
    id: "7",
    name: "Training shoes",
    href: "#",
    price: 49.99,
    color: "black",
    size: "42",
    imageSrc: "https://nextuipro.nyc3.cdn.digitaloceanspaces.com/components-images/shoes/7.png",
  },
  {
    id: "8",
    name: "Sneakers",
    href: "#",
    price: 29.99,
    color: "red",
    size: "42",
    imageSrc: "https://nextuipro.nyc3.cdn.digitaloceanspaces.com/components-images/shoes/8.png",
  },
  {
    id: "9",
    name: "Running shoes",
    href: "#",
    price: 39.99,
    color: "blue",
    size: "42",
    imageSrc: "https://nextuipro.nyc3.cdn.digitaloceanspaces.com/components-images/shoes/19.png",
  },
];

export default products;
